### ISSUE TITLE
Revisit ProductIndexer implementation

### ISSUE THREAD

**Issue by tanzb33r** [shopwareArchive/proposal#46]
**Effort**: high

### Description:
When upserting products via the DAL the ProductIndexer takes up to 90% of the consumed time. 
Especially the StockUpdater, ProductStreamUpdater and CheapestPriceUpdater seem to be worth looking at.
I would suggest to do performance tests on a bigger dataset with at least 25k products and multiple prize rules and also optimize the database datastructure.

### Benefits
Reducing upsert time of products significantly.

### Break strategy
I would assume these functions are mainly used internally and therefor cause little to no breaking changes for others

**Comment by OliverSkroblin** [comment]
Hi @tanzb33r,

thanks for your contribution. In our proposals we are collecting breaking change topics for the next major version. 

Your issue would be more of a bug or performance issue and should go through our issue tracker normally. However, there is already a proposal about performance and scalability, so maybe you can transfer your suggestions to this one:  https://github.com/shopware/platform/issues/3140
